[package]
name = "gg"
version = "0.1.0"
authors = [
    "Zageron <hello@adambryant.ca>",
    "Aztek <andrew.cc.osborne@gmail.com>",
    "Rael <callum.mcrae5@gmail.com>",
]
edition = "2018"

[profile.dev.package.'*']
opt-level = 3

[dependencies]
bevy = "0.3.0"
rand = "0.7.3"
